# build the application using the Go toolset image
FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
RUN go mod tidy && go build -o guestbook-api .

# run
FROM golang:1.24-alpine AS runtime
WORKDIR /app
COPY --from=builder /app/guestbook-api .
EXPOSE 8080
CMD ["./guestbook-api"]
